#!/usr/bin/env python

import os
import logging
from libdotify import utils

PLUGINS = [
    "https://github.com/sjl/gundo.vim.git",
    "https://github.com/altercation/vim-colors-solarized.git",
    "https://github.com/morhetz/gruvbox.git",
    "https://github.com/christoomey/vim-tmux-navigator",
    "https://github.com/tomtom/tcomment_vim.git",
    "https://github.com/tpope/vim-pathogen.git",
    "https://github.com/xolox/vim-misc.git",
    "https://github.com/xolox/vim-easytags.git",
    "https://github.com/majutsushi/tagbar.git",
    "https://github.com/vim-airline/vim-airline.git",
    "https://github.com/vim-airline/vim-airline-themes.git",
    "https://github.com/tpope/vim-fugitive.git",
]

def update(args, dst):
    dst = "{}/bundle/".format(dst)
    if not os.path.exists(dst):
        os.makedirs(dst)

    utils.git_update("vim", dst, PLUGINS)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
