#!/usr/bin/env python

import os
import logging
from libdotify import utils

PLUGINS = [
    "git://github.com/joel-porquet/zsh-dircolors-solarized"
]

def update(args, dst):
    if not os.path.exists(dst):
        os.makedirs(dst)
    utils.git_update("oh-my-zsh", "{}/plugins/".format(dst), PLUGINS)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
