#!/usr/bin/env python

import os
import logging
from libdotify import utils

PLUGINS = [
    "https://github.com/tobi-wan-kenobi/bumblebee-status.git",
]

def update(args, dst):
    dst = "{}/".format(dst)

    utils.git_update("i3", dst, PLUGINS)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
