export PATH=~/bin:$PATH
export EDITOR=nvim
export BAT_THEME=gruvbox-light

alias vim="nvim"
alias vimf="nvim \$(fzf)"

bindkey -e

COMPLETION_WAITING_DOTS="true"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"

source $HOME/.config/zsh/antigen.zsh

function bgnotify_formatted {
	[ $1 -eq 0 ] && {
		title="success"
		additional="<b><span color='#b8bb26'>OK</span></b>"
	} || {
		title="failure"
		additional="<b><span color='#fb4934'>ERROR</span></b>"
	}
	duration=$(date -ud "@$3" +'%T')
	[ $1 -eq 0 ] && title="success" || title="failure"
	bgnotify "$title after $duration" "$2<br/>$additional"
}

antigen use oh-my-zsh
antigen bundle git
antigen bundle pass
antigen bundle bgnotify
antigen bundle command-not-found
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions

zstyle :omz:plugins:ssh-agent agent-forwarding on

antigen apply

if [ -f /usr/share/doc/fzf/key-bindings.zsh ]; then
	source /usr/share/doc/fzf/key-bindings.zsh
fi

if [ -f /usr/share/fzf/key-bindings.zsh ]; then
	source /usr/share/fzf/key-bindings.zsh
fi

if [ -f $HOME/src/git-subrepo/.rc ]; then
	source $HOME/src/git-subrepo/.rc
fi

if [ -n "$DESKTOP_SESSION" ]; then
	eval $(gnome-keyring-daemon --start)
	export SSH_AUTH_SOCK
fi

if [ -f $HOME/.cargo/env ]; then
	source $HOME/.cargo/env
fi

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

export FZF_DEFAULT_COMMAND='rg --files --ignore-vcs --hidden --glob "!ccache/"'
