export PATH=~/bin:$PATH
export EDITOR=nvim
export BAT_THEME=gruvbox-light

alias vim="nvim"

bindkey -e

COMPLETION_WAITING_DOTS="true"

source $HOME/.config/zsh/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle pass
antigen bundle ssh-agent
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions

zstyle :omz:plugins:ssh-agent agent-forwarding on

antigen apply

eval "$(starship init zsh)"
