#!/usr/bin/env python

import os
import logging
from libdotify import utils

PLUGINS = [
    "https://github.com/seebi/dircolors-solarized.git"
]

def update(args, dst):
    dst = "{}/".format(dst)

    utils.git_update("dircolors", dst, PLUGINS)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
